apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: virtualvuelo-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: virtualvuelo-app
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - path: /actuator/prometheus
      port: http
      interval: 15s